### ISSUE TITLE
Experimental 4 error

### ISSUE THREAD

**Issue by handsomepig** [pokesniperandroid/PokeSniper-Android#128]
When I go to my pokebag the app freezes. Also, whenever I go to snipe it gives me this "no more (Pokemon) to catch"

**Comment by handsomepig** [comment]
It also says "Request to server couldn't be started"

**Comment by SamuelPGM** [comment]
When it says : there is no more pokemon to catch, is because you were too late to catch that pokemon, and for me, when I first try to snipe, thathe message appears: "Request To Server couldn't be found", buthere then I snipe again and I doesn't show it up never again... and pokebag it's all right to me.....

**Comment by pokesniperandroid** [comment]
@handsomepig are still facing this issue? try to force stop the app and reopen again.

**Comment by lac2811** [comment]
@pokesniperandroid "EXPERIMENTAL6" have this issue #103 yet. 

Regardless the app remains incredible!

**Comment by handsomepig** [comment]
I am pokesniperandroid

**Comment by pokesniperandroid** [comment]
pokebag fixed in 1.5.7-BETA1
