### ISSUE TITLE
Have a problem

### ISSUE THREAD

**Issue by Kwasny3** [pokesniperandroid/PokeSniper-Android#144]
I have a problem So I have the latest version v1.5.7 pokesniper do everything worked well today because somewhere until 9 application to work and now (ie 11:23) as I want to catch pokemon pops up that you are logged, and so on and then writes No more larvitar and so for each

**Comment by pokesniperandroid** [comment]
Try with different account, we could catch larvitar without error just now

<img src="http://i.imgur.com/zX6UkbY.png" width="60%" />

**Comment by pokesniperandroid** [comment]
@Kwasny3 are you still facing this error? if not, i'll close this issue.

**Comment by Kwasny3** [comment]
Unfortunately, we still do not like trying to catch, for example, eevee it says "No more Eevee is cautch" I've tried 3 times to 2 accounts with other Pokémon what to do :(

**Comment by pokesniperandroid** [comment]
Try with another devices or emulator with your tested account.

**Comment by Kwasny3** [comment]
Do not quite understand yet ai pokesniper yesterday worked me well

**Comment by pokesniperandroid** [comment]
So, is everything working?

**Comment by ewanewan** [comment]
Hi sir..i got 3 acc using pokesniper without problems but 1 of my acc always fail to snipe..everytime i try to snipe its appers d.a.a.c$a....lil bit confiuse coz other 3acc didnt face that problem..(all google acc)tnx in advance sir

**Comment by Kwasny3** [comment]
Again, I have a problem I did as radziłeś logged on PTC (Today) and now I can again catch Pokemon yet moments ago I c

**Comment by Kwasny3** [comment]
I logged in to your google account 3 and now works but I assume that tomorrow they will stop working to fix it in the next update?

**Comment by Kwasny3** [comment]
Because I'm tired all the time I have to change the angle?! it is pointless better quickly repairs

**Comment by pokesniperandroid** [comment]
@ewanewan if you get response d.a.a.c$a or token exception, login request has been denied by google because the app get invalid token.


@Kwasny3 if your problem is account related, i don't think this app bug, because Niantic could be flagging any account and our app couldn't help this kind of case because its their server. we never face issue(s) except when API changes.

pokemon go API only simulate the real app and <b>probably</b> could be detected by Niantic easily.

if there's no pokemon (says 0 pokemon in sight), the response from Niantic could be delayed, try again. if you get same response then read the reason below.

if there's no more specific pokemon when there's pokemon(s) in sight (like "no more ditto to catch), this could be the said pokemon was gone or despawned or has been catched by n number of people. this also apply to when there's only one pokemon and has been gone or despawned

**Comment by Kwasny3** [comment]
Thank you for your help already did it, thanks awfully for your help. Aplikcja I like Greetings and look forward to more exciting update :)

**Comment by ewanewan** [comment]
@ewanewan if you get response d.a.a.c$a or token exception, login request has been denied by google because the app get invalid token.
☝ any suggestions sir?becouse  i try with latest release but still face the problem.

**Comment by pokesniperandroid** [comment]
@ewanewan try with different account or try this method by Google https://support.google.com/accounts/answer/185833?hl=en

**Comment by ewanewan** [comment]
@ewanewan try with different account or try this method by Google https://support.google.com/accounts/answer/185833?hl=en
OMG its working! Really appreciate it sir!! Thats why i love pokesniper..always helpfull..God bless!!
