### ISSUE TITLE
Pokemon coordinates 

### ISSUE THREAD

**Issue by klayscott** [pokesniperandroid/PokeSniper-Android#149]
Hi guys thanks for the hard work the app is great again , but i just want a list of coordinates sites besides pokezz and mypogosnipers if that possible thanks , p.s mypogosniper no longuer free....

**Comment by MrCrunchy** [comment]
https://bestforandroid.com/pokezz-alternatives/

**Comment by KHARUROSU** [comment]
You can go to pokedex100.com 
It's what i do, copy the coordinates and insert them in the APP.

**Comment by ryanbks8000x** [comment]
Use this discord server
https://discord.gg/9WGZNMm

**Comment by klayscott** [comment]
Alright thanks guys

**Comment by Av1s** [comment]
guys remember to close the issues when it is sorted out...@klayscott

**Comment by Ebehuecos** [comment]
Guys why I keep having problem with there was no pokemon was found ?

**Comment by pokesniperandroid** [comment]
@Ebehuecos did you try with different account? no pokemon = 0 pokemon in sight?

**Comment by Ebehuecos** [comment]
No not 0 pokemon in sight it just can't snipe any pokemon

On 3 Mar 2017 9:27 p.m., "pokesniperandroid" <notifications@github.com>
wrote:

@Ebehuecos <https://github.com/Ebehuecos> did you try with different
account? no pokemon = 0 pokemon in sight?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/pokesniperandroid/PokeSniper-Android/issues/149#issuecomment-283952289>,
or mute the thread

**Comment by pokesniperandroid** [comment]
@Ebehuecos umm, okay. can you provide more info than that? like what the log says?

**Comment by Ebehuecos** [comment]
Nvm problem solved
