### ISSUE TITLE
Returning Null

### ISSUE THREAD

**Issue by jackhiggins138** [pokesniperandroid/PokeSniper-Android#15]
using http://www.pokesnipers.com/ and the "snipe me" option. does everything till the capture bit and just returns Null. it was working fine before but now all i am getting is "null". i can log in using PokemonGO and everything normal works but can't "snipe" anymore

**Comment by xfewlink** [comment]
Same with me. i also received the same error with jack.

**Comment by jackhiggins138** [comment]
Did some testing, you get this "error" if you have no pokeballs left.

i'll probably make a pullrequest giving a better error message at somepoint if it's not fixed

**Comment by kingkai808** [comment]
Can you add use any type ball? In next release and more anti ban detection? Great app! I'm just skeptical of being banned this is too good.

**Comment by jackhiggins138** [comment]
I mean, it's not my Repo. i'll try my best to make the pullrequest but not up to me if it gets added

**Comment by pokesniperandroid** [comment]
hello, sorry for the long update. currently the messages was updated but the updated version is not released yet because still in testing phase. there'll be pokeball info (master, ultra, great or standard), razzberryinfo (if there's razzberry, it will be used), catch status (success, flee or escape) if it's escape, the app will try to catch again. and there's implementation about multiple accounts and pokedex & inventory. so, for now bear with the current version. thanks :)
