### ISSUE TITLE
no more pokemon to catch

### ISSUE THREAD

**Issue by zabuza8** [pokesniperandroid/PokeSniper-Android#17]
Something wrong?

**Comment by pokesniperandroid** [comment]
hello, sorry for the long update. currently the messages was updated but the updated version is not released yet because still in testing phase. there'll be pokeball info (master, ultra, great or standard), razzberryinfo (if there's razzberry, it will be used), catch status (success, flee or escape) if it's escape, the app will try to catch again. and there's implementation about multiple accounts and pokedex & inventory. so, for now bear with the current version. sorry for the inconvenience and thanks
