### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by lukmansyah** [pokesniperandroid/PokeSniper-Android#177]
"You need Pokehash key to snipe"
Why??? how to handle it ???
whereas,i have try BETA 10

**Comment by pokesniperandroid** [comment]
Read instruction in release page

**Comment by chimsedinang123** [comment]
When the API is inherited, the purchase of the hashkey is still half-hearted you.

 Why buy a hashkey to run is not safe.

May be niantic fraud. It happened at 0.49.

Niantic hides a code in version 0.49 to detect robots.

**Comment by pokesniperandroid** [comment]
Even when using legacy API, third-party apps still detected either way. The key was the only thing that let the app run again, because the legacy API is dead right now. The decision to buy is on you, whether it's worth it or not. We give shared key beforehand, so you get to test it.

And for your information, the key is only used for hashing the request not to catch the pokemon nor doing any action related that. The request is hashed (something like encrypted data) so the Niantic server could give valid response, beyond that is handled by API (the user-interaction logic: catching, transfer, etc). The hashing service was released because the hashing algorithm was never released to public. Had been discussed a while ago in reddit the reason, forgot the link.

**Comment by chimsedinang123** [comment]
Thank you very much . The team is professional. And now I understand

**Comment by chimsedinang123** [comment]
How long does a key last? Maximum usage on multiple accounts. Thank

**Comment by pokesniperandroid** [comment]
31 days since first use. If you use our shared key, it's limited to 150 users/minute. If the users/minute is more than that, you'll get error response or no pokemon.
