### ISSUE TITLE
catch region-exclusive

### ISSUE THREAD

**Issue by mokenneth** [pokesniperandroid/PokeSniper-Android#86]
I live in HK and would like to catch other region-exclusive, Mr Mine, can i seek your suggestion in setting of the 'Home Coordinates' to avoid soft/perm. ban?

**Comment by MrCrunchy** [comment]
set home coordinate to where you logged in to app last or most often.

**Comment by mokenneth** [comment]
will it be more safety if i stop to login the game 2 days(pay safe as travel time to London from HK is around 24 hrs),  then set the home coordinates same as the target pokemon location and sniper it,  and login the game after 2 days?

**Comment by parind** [comment]
Sniping Pokemon is legal in the game till yet. What it does is after you find a Location of a Far Away Pokemon and you teleport to that location. Dont move or Open Any Pokestops. And just as soon as the Pokemon Appears, tapping on it takes you to the Catch Pokemon Screen. Dont Throw any ball it would ban you so Minimise the game (Dont Close it) and Set the co-ordinates to your Home Co-ordinate and then open the Game and throw Pokeballs it will get caught. This is the method if you want to use without Pokesniper. Whereas Pokesniper just does this work in 9-10 seconds. And yes No one have yet been banned due to Sniping and it is a bug in the game so it is legal too. Play Safe.

**Comment by mokenneth** [comment]
thanks a lot
